name: KBOT_TELE_TOKEN

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - token_changed

jobs:
  token_change:
    name: TOKEN_CHANGE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Authentification to GCP SecretManager'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Obtain TELE_TOKEN'
        id: secrets
        uses: 'google-github-actions/get-secretmanager-secrets@v1'
        with:
          secrets: |-
            tele_token:352350778257/TELE_TOKEN
      - name: 'Save TELE_TOKEN'
        run: |
          echo "TELE_TOKEN=${{ steps.secrets.outputs.tele_token }}" >> $GITHUB_ENV
      - name: 'show TELE_TOKEN'
        run: echo ${{ env.TELE_TOKEN }}
