name: KBOT_TELE_TOKEN

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - token_changed

jobs:
  token_change:
    name: TOKEN_CHANGE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Authentification to GCP SecretManager'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Obtain TELE_TOKEN'
        id: secrets
        uses: 'google-github-actions/get-secretmanager-secrets@v1'
        with:
          secrets: |-
            tele_token:352350778257/TELE_TOKEN
      - name: 'Save TELE_TOKEN'
        run: |
          echo "TELE_TOKEN=${{ steps.secrets.outputs.tele_token }}" >> $GITHUB_ENV
      - name: 'Show TELE_TOKEN'
        run: echo ${{ env.TELE_TOKEN }}
      
      - name: 'get-credentials for kubernetes cluster'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'main'
          project_id: 'k8s-k3s-386218'
          location: 'us-central1-c'

      # The KUBECONFIG env var is automatically exported and picked up by kubectl.
      - name: 'get-pods'
        run: 'kubectl get pods -n demo'
      
      - name: Create not encrypted secret.yaml
        run: kubectl -n demo create secret generic kbot --from-literal=token=$TELE_TOKEN --dry-run=client -o yaml > secret.yaml
      - name: Show secret.yaml
        run: cat secret.yaml

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.4.1
        with:
          version: latest
      - name: Encrypt secret.yaml    
        run: sops-path -e -gcp-kms projects/k8s-k3s-386218/locations/global/keyRings/sops-flux-v2/cryptoKeys/sops-key-flux-v2 --encrypted-regex '^(token)$' secret.yaml>./clusters/demo/secret-encrypted.yaml
